# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-basics-state"
    dynamodb_table = "terraform-basics-locks"
    encrypt        = true
    key            = "dev/terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
